apiVersion: v1
kind: Template
metadata:
  name: mattermost
  annotations:
    openshift.io/display-name: "Mattermost Team (Opensource)"
    description: "Template to provision a Mattermost Team instance."
    iconClass: "icon-bubbles"
    tags: "instant-app,mattermost,slack"
  creationTimestamp: null
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "mattermost-config"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "mattermost-logs"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: mattermost
    name: mattermost
  spec:
    replicas: 1
    selector:
      service: mattermost
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 1Gi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
      triggers:
        - type: ConfigChange
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mattermost
          name: "mattermost"
      spec:
        containers:
        - name: mattermost
          image: registry.centos.org/mattermost/mattermost-team:${IMAGE_TAG}
          ports:
          - containerPort: 8065
            protocol: TCP
          env:
          - name: MM_DB_HOST
            value: "postgres"
          - name: MM_DB_PORT
            value: "5432"
          - name: MM_DB_USER
            value: "mattermost"
          - name: MM_DB_PASS
            value: "password"
          - name: MM_DB_NAME
            value: "userdb"
          volumeMounts:
            - name: mattermost-config
              mountPath: "/opt/mattermost/config"
              readOnly: false
            - name: mattermost-logs
              mountPath: "/opt/mattermost/logs"
              readOnly: false
        volumes:
          - name: mattermost-config
            persistentVolumeClaim:
              claimName: "mattermost-config"
          - name: mattermost-logs
            persistentVolumeClaim:
              claimName: "mattermost-logs"
        terminationMessagePath: "/dev/termination-log"
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 8065
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8065
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

      restartPolicy: Always
      dnsPolicy: ClusterFirst
- kind: Service
  apiVersion: v1
  metadata:
    creationTimestamp: null
    labels: 
      service: mattermost
    name: "mattermost"
  spec:
    ports:
    - name: mattermost
      port: 8065
      targetPort: 8065
      protocol: TCP
    selector:
      service: "mattermost"
    sessionAffinity: None
    type: ClusterIP
- kind: Route
  apiVersion: v1
  metadata:
    creationTimestamp: null
    labels: 
      service: mattermost
    name: "mattermost"
  spec:
    host: ''
    port:
      targetPort: 8065
    to:
      kind: Service
      name: "mattermost"
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE_TAG
  value: "4.8"
