apiVersion: v1
kind: Template 
metadata:
  name: postgres
  annotations:
    openshift.io/display-name: "PostgreSQL"
    description: "PostgreSQL openshift Example"
    iconClass: "icon-database"
    tags: "database,postgresql"
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "pgdata"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: null
    labels:
      app: postgresql
      name: postgres
    name: postgres
  spec:
    containers:
    - env:
      - name: POSTGRESQL_USER
        value: mattermost
      - name: POSTGRESQL_PASSWORD
        value: password
      - name: POSTGRESQL_DATABASE
        value: userdb
      - name: POSTGRESQL_ADMIN_PASSWORD
        value: password
      image: registry.centos.org/centos/postgresql-95-centos7:latest
      imagePullPolicy: Always
      name: postgres
      ports:
      - containerPort: 5432
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      volumeMounts:
      - mountPath: /var/lib/pgsql/data
        name: pgdata
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
    volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: pgdata
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql
      name: postgres
    name: postgres
  spec:
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
